### ISSUE TITLE
Dependabot not finding outdated actions outside of workflows

### ISSUE THREAD

**Issue by steveoh** [agrc/roadkill-mobile#344]
Custom actions in the `.github/actions` directory are not being seen by dependabots current configuration:

```yml
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: staging
    schedule:
      interval: monthly
    groups:
      ci-dependencies:
        dependency-type: 'production'
```

These custom actions are used in a few other repositories and this fix should ripple through those repos.

- [ ] agrc/deq-eid-skid
- [ ] agrc/gcp-terraform 
- [ ] agrc/project-moonwalk
- [ ] agrc/nfhl-skid
- [ ] agrc/porter
- [ ] agrc/wmrc-skid

A couple ideas to try could be 

- [ ] Moving the `.github/actions` folder to be a sibling of `.github/workflows` to determine if dependabot is only searching in the `.github/workflows` directory by convention.
- [ ] Migrate the `directory` prop to `directories` adding the custom location.

	```yml
	updates:
	  - package-ecosystem: github-actions
	    directories: 
	      - /
	      - .github/actions
	    target-branch: staging
	    schedule:
	      interval: monthly
	    groups:
	      ci-dependencies:
	        dependency-type: 'production'
	```
